[package]
name = "bech32"
version = "0.3.0"
authors = ["Clark Moody"]
repository = "https://github.com/clarkmoody/rust-bech32"
description = "Encodes and decodes the Bech32 format"
readme = "README.md"
keywords = ["base32", "encoding", "bech32"]
categories = ["encoding"]
license = "MIT"

[dependencies]
